### ISSUE TITLE
Where to download?

### ISSUE THREAD

**Issue by EverNife** [ezeiger92/QuestWorld-Extensions#1]
Can you make a release for me to download please :D

**Comment by Zicerite** [comment]
Go to the main page, select releases, then at the bottom of the most recent release post, is where you will find the download

**Comment by Zicerite** [comment]
Er well, once its released anyway...

**Comment by EverNife** [comment]
🤦‍♂️ That i know my friend...

What I was asking was whether or not there is some release available to us.
Sometimes developers forget to let theses builds on github '-'

**Comment by ezeiger92** [comment]
I got busy with life, then I got busy trying to replace menus in questworld. Once that gets sorted out, everything will get uploaded.

**Comment by Fharen** [comment]
I tried compiling this. Sadly, I failed.
It seems the compilation process for addon plugins is different.
can anyone teach me how?

**Comment by ezeiger92** [comment]
Again, I haven't pushed out a build that even would use these. I'm quite low on free time right now, but am still working on things

**Comment by ezeiger92** [comment]
[QuestWorld 2.6.8 (Decoupled Edition)](https://github.com/ezeiger92/QuestWorld2/releases/tag/v2.6.8-beta)
