### ISSUE TITLE
Extensions  Invalid plugin.yml

### ISSUE THREAD

**Issue by StpNex** [ezeiger92/QuestWorld-Extensions#4]
[11:40:09] [Server thread/ERROR]: Could not load 'plugins\QW-Mythic-0.1.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml

I compiled it myself but even the Jars you release dont have a plugin.yml?

**Comment by ezeiger92** [comment]
I'll assume you figured this out yourself, but I'll leave a comment for anyone else wandering by: Extensions should be placed in the QuestWorld/extensions/ folder, not the plugins folder
